name: Test Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Starting first run on github action"
      
      - name: List files
        run: ls

      - name: show readme
        run: cat README.md